### ISSUE TITLE
Flow of tilt compensation process

### ISSUE THREAD

**Issue by jasvinder1079** [sparkfun/SparkFun_IM19_IMU_Arduino_Library#1]
Hello @nseidle ,
Thanks for this library. I want to know the working flow of IM19 tilt compensation process like how all the mentioned API's will work together.

**Comment by nseidle** [comment]
The IM19 is used in only one of our products, the [RTK Torch](https://www.sparkfun.com/products/25662). You can view the main/only use of this library in the code base for the Torch, mostly in [Tilt.ino](https://github.com/sparkfun/SparkFun_RTK_Everywhere_Firmware/blob/main/Firmware/RTK_Everywhere/Tilt.ino). I hope this helps!
